<footer class="footer">
    <div class="footer-container">
      <div class="footer-row">
        <div class="footer-col">
          <h3>Company</h3>
          <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="jobs.php">Positions</a></li>
            <li><a href="apply.php">Application</a></li>
            <li><a href="about.php">About Us</a></li>
            <li><a href="phpenhancements.php">Enhancements</a></li>
          </ul>
        </div>
        <div class="footer-col">
          <h3>Copyright &copy;</h3>
          <ul>
            <li><a href="https://www.swinburne.edu.au">Swinburne University of Technology</a></li>
            <li><a href="https://www.pinterest.com.au">Pinterest</a></li>
            <li><a href="https://www.freepik.com">Freepik</a></li>
            <li><a href="https://www.canva.com">Canva</a></li>

          </ul>
        </div>
        <div class="footer-col">
          <h3>Contact Us</h3>
          <ul>
            <li><a href="mailto:104772183@student.swin.edu.au">Khoi Nguyen Pham</a></li>
            <li><a href="mailto:104201881@student.swin.edu.au">Ngykeang Oeung</a></li>
            <li><a href="mailto:14172343@student.swin.edu.au">Monytola Long</a></li>
          </ul>
        </div>
      </div>
    </div>
 </footer>