<nav> 

      <a href="index.php"><img src="images/spotifree.png" alt="logo"></a>
      <div class="nav-links" id="navlinks">

        <ul>
          <li><a href="index.php">HOME</a></li>
          <li><a href="jobs.php">POSITIONS</a></li>
          <li><a href="apply.php">APPLICATION</a></li>
          <li><a href="about.php">ABOUT US</a></li>
          <li><a href="phpenhancements.php">ENHANCEMENTS</a></li>
          <li><a href="login.php">LOGIN</a></li>
        </ul>
      </div>

    </nav>